# Generated by Django 4.1.2 on 2022-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='net_sales',
            field=models.FloatField(),
        ),
    ]
